QHBoxLayout*	GetMainLayout();
JYWidget*	GetTopListWidget();
JYWidget*	GetHistogramWidget();
JYWidget*	GetBottomWidget();
QListView*	GetStudentListView();
QLabel*	GetCountLabel();
QPushButton*	GetScreenBtn();
QPushButton*	GetStopBtn();
QPushButton*	GetCancleBtn();
